# Generated by Django 4.2 on 2023-06-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsFilesStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='userassets/posts_images/')),
                ('image_name', models.CharField(default=None, max_length=100, null=True)),
                ('notes_file', models.FileField(upload_to='userassets/posts_files/')),
                ('notes_file_name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(default=None, max_length=12000, null=True)),
                ('is_drafted', models.BooleanField(default=False)),
                ('community', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
        ),
    ]
