# Generated by Django 4.2 on 2023-06-19 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='downvotes_users',
            field=models.ManyToManyField(null=True, related_name='posts_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.ManyToManyField(related_name='post', to='posts.postsfilesstore'),
        ),
        migrations.AddField(
            model_name='posts',
            name='upvotes_users',
            field=models.ManyToManyField(null=True, related_name='posts_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
