# Generated by Django 4.2 on 2023-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsfilesstore',
            name='image',
            field=models.ImageField(default=None, upload_to='userassets/posts_images/'),
        ),
        migrations.AlterField(
            model_name='postsfilesstore',
            name='notes_file',
            field=models.FileField(default=None, upload_to='userassets/posts_files/'),
        ),
    ]
