# Generated by Django 4.2 on 2023-06-21 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_postsfilesstore_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='downvotes_users',
            field=models.ManyToManyField(related_name='posts_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='upvotes_users',
            field=models.ManyToManyField(related_name='posts_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
