# Generated by Django 4.2 on 2023-06-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='reply_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
