# Generated by Django 4.2 on 2023-06-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.SmallIntegerField(default=1),
        ),
    ]
