# Generated by Django 4.2 on 2023-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(default=None, max_length=25)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('icon_path', models.ImageField(default=None, null=True, upload_to='userassets/community_icons/')),
            ],
        ),
    ]
