# Generated by Django 4.2 on 2023-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_community_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(db_collation='utf8mb4_general_ci', max_length=25),
        ),
    ]
